name: Server snapshot → server-snapshot

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Por qué se lanzó el snapshot"
        required: false
        default: "manual"
      initiator:
        description: "Quién inició la solicitud (se completa automáticamente desde WordPress)"
        required: false
        default: ""
      environment:
        description: "Entorno o dominio origen (se completa automáticamente desde WordPress)"
        required: false
        default: ""

# Necesita permiso para commitear a la rama server-snapshot
permissions:
  contents: write

# Evita ejecutar dos snapshots a la vez
concurrency:
  group: snapshot
  cancel-in-progress: false

jobs:
  snapshot:
    runs-on: ubuntu-latest

    # TUS DATOS (no sensibles) → ajusta aquí si lo necesitas
    env:
      FTP_SERVER: ftp.scios.club
      FTP_USERNAME: gith@scios.club
      FTP_PORT: 21
      # Si el home del usuario FTP es /public_html/wp-content, deja '.'
      # Si el home es la raíz del hosting, cambia a: public_html/wp-content
      FTP_REMOTE_DIR: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Prepare server-snapshot branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          if git ls-remote --exit-code --heads origin server-snapshot >/dev/null 2>&1; then
            git fetch origin server-snapshot
            git checkout server-snapshot
          else
            git checkout --orphan server-snapshot
            rm -rf *
            git commit --allow-empty -m "Initialize server-snapshot"
            git push origin server-snapshot
          fi

          rm -rf snapshot
          mkdir -p snapshot/wp-content

      - name: Mirror wp-content via FTPS (explicit TLS) EXCLUDING selected plugins
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          : "${FTP_PORT:=21}"
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -p "$FTP_PORT" "ftp://$FTP_SERVER" <<LFTP
          set ssl:verify-certificate no
          set ftp:ssl-force true
          set ftp:ssl-protect-data true
          set net:timeout 30
          set net:max-retries 2
          set net:persist-retries 1
          set cmd:fail-exit yes

          mirror --verbose --only-newer --parallel=4 \
            --exclude-glob ai1wm-backups/** \
            --exclude-glob cache/** \
            --exclude-glob upgrade/** \
            --exclude-glob upgrade-temp-backup/** \
            --exclude-glob uploads/** \
            --exclude-glob jetpack-waf/** \
            --exclude-glob webp-express/** \
            --exclude-glob wp-rocket-config/** \
            --exclude-glob *.log \
            --exclude-glob debug.log \
            --exclude-glob temp-write-test* \
            --exclude-glob plugins/3d-viewer/** \
            --exclude-glob plugins/all-in-one-seo-pack/** \
            --exclude-glob plugins/all-in-one-wp-migration/** \
            --exclude-glob plugins/all-in-one-wp-migration-unlimited-extension/** \
            --exclude-glob plugins/click-to-chat-for-whatsapp/** \
            --exclude-glob plugins/duplicate-page/** \
            --exclude-glob plugins/google-analytics-for-wordpress/** \
            --exclude-glob plugins/google-analytics-premium/** \
            --exclude-glob plugins/google-listings-and-ads/** \
            --exclude-glob plugins/jetpack/** \
            --exclude-glob plugins/mailpoet/** \
            --exclude-glob plugins/one-click-demo-import/** \
            --exclude-glob plugins/optinmonster/** \
            --exclude-glob plugins/revslider/** \
            --exclude-glob plugins/webinar-and-video-conference-with-jitsi-meet/** \
            --exclude-glob plugins/wemail/** \
            --exclude-glob plugins/woocommerce-conversion-tracking/** \
            --exclude-glob plugins/woocommerce-custom-fields/** \
            --exclude-glob plugins/woocommerce-gateway-paypal-express-checkout/** \
            --exclude-glob plugins/wordpress-seo/** \
            --exclude-glob plugins/wordpress-seo-premium/** \
            --exclude-glob plugins/wp-crowdfunding/** \
            --exclude-glob plugins/wp-file-manager/** \
            --exclude-glob plugins/wp-job-manager/** \
            --exclude-glob plugins/wp-whatsapp-chat/** \
            --exclude-glob plugins/wpseo-woocommerce/** \
            "$FTP_REMOTE_DIR" snapshot/wp-content
          bye
          LFTP


      - name: Copy into repo layout
        run: |
          mkdir -p wp-content
          rsync -a --delete snapshot/wp-content/ wp-content/

      - name: Commit & push if changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            TS="$(date -u +'%Y-%m-%d %H:%M:%S') UTC"
            REASON="${{ github.event.inputs.reason }}"
            git commit -m "Server snapshot: ${REASON:-manual} (${TS})"
            git push origin server-snapshot
          fi
